version: '3.8'

services:
  mafia-backend:
    build: ./backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mafia
    ports:
      - "8080:8080"

  mafia-frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - mafia-backend

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mafia

volumes:
  postgres_data: