services:
  mafia-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: runtime
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mafia
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  mafia-backend-tests:
    profiles:
      - tests
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: tester_base
    volumes:
      - ./backend/src:/app/src:ro
      - ./backend/pom.xml:/app/pom.xml:ro
      - test-reports:/app/target/surefire-reports
    command: sh -c " \
      echo 'Starting integration tests with H2 database...' && \
      rm -rf /app/target/surefire-reports/* && \
      mvn test \
      -Dspring.profiles.active=test \
      -Dlogging.level.com.mafia=INFO \
      -Dmaven.test.failure.ignore=false \
      "
    environment:
      - SPRING_PROFILES_ACTIVE=test

  mafia-frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - mafia-backend

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=mafia
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mafia"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  rabbitmq_data:
  test-reports:
